name: myecl
description: A new Flutter project.

publish_to: "none"
version: 0.5.5+70

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  collection: ^1.16.0
  crypto: ^3.0.2
  datetime_picker_formfield: ^2.0.1
  dotenv: ^4.0.1
  either_dart: ^1.0.0
  fl_chart: ^0.63.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.0.0
  heroicons: ^0.8.0
  hooks_riverpod: ^2.1.1
  http: ^1.0.0
  http_parser: ^4.0.2
  image_cropper: ^5.0.0
  image_picker: ^1.0.0
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  numberpicker: ^2.1.1
  package_info_plus: ^4.0.2
  path: ^1.8.2
  path_provider: ^2.0.11
  qlevar_router: ^1.9.0
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_calendar: ^22.1.36
  tuple: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.7
  vector_math: ^2.1.2
  zxcvbn: ^1.0.0

dev_dependencies:
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/logo.png
    - assets/images/gift.png
    - assets/images/soli.png
    - assets/images/eclair.png
    - assets/images/login.svg
    - assets/images/back.jpg

  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios:
    generate: true
    image_path: "assets/images/icon.jpg"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
