name: myecl
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.1
  flash: ^2.0.3+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_riverpod: ^1.0.3
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  heroicons: ^0.4.0
  hooks_riverpod: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  jwt_decoder: ^2.0.1
  numberpicker: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_calendar: ^20.1.50
  tuple: ^2.0.0
  uni_links: ^0.5.1
  uuid: ^3.0.6

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/test3.jpg

  uses-material-design: true
