name: titan
description: Titan est le frontend d'une application de gestion de la vie associative

publish_to: "none"
version: 2.0.5+163
# https://dart.dev/tools/pub/pubspec : "Pub ignores all other fields."
minimal_hyperion_version: 5.0.2

environment:
  sdk: ^3.10.0
  flutter: ^3.38.6

dependencies:
  app_links: ^6.4.0
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  collection: ^1.16.0
  crypto: ^3.0.2
  cryptography_plus: ^2.0.0
  datetime_picker_formfield: ^2.0.1
  device_info_plus: ^11.4.0
  diacritic: ^0.1.5
  either_dart: ^1.0.0
  file_picker: ^10.1.2
  file_saver: ^0.2.12
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.2
  fl_chart: ^1.0.0
  flash: ^3.1.1
  flutter:
    sdk: flutter
  flutter_appauth: ^9.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.21.2
  flutter_lints: ^6.0.0
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18+3
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^10.0.0-beta
  flutter_svg: ^2.0.7
  google_fonts: ^7.0.0
  heroicons: ^0.11.0
  hooks_riverpod: ^2.1.1
  http: ^1.0.0
  http_parser: ^4.0.2
  image: ^4.0.15
  image_cropper: ^9.0.0
  image_picker: ^1.0.0
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  load_switch: ^2.0.5
  local_auth: ^2.3.0
  local_auth_android: ^1.0.46
  local_auth_darwin: ^1.4.1
  mobile_scanner: ^7.0.1
  numberpicker: ^2.1.1
  package_info_plus: ^8.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  pdfx: ^2.9.1
  permission_handler: ^12.0.0+1
  qlevar_router: ^1.9.0
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_calendar: ^29.1.38
  timeago: ^3.7.0
  timezone: ^0.10.0
  tuple: ^2.0.0
  universal_html: ^2.0.8
  url_launcher: ^6.2.5
  uuid: ^4.5.1
  webview_flutter: ^4.10.0
  yaml: ^3.1.3

dev_dependencies:
  dependency_validator: ^5.0.2
  dotenv: ^4.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  vector_math: ^2.1.2

flutter:
  assets:
    - .env
    - pubspec.yaml
    - assets/images/logo_prod.png
    - assets/images/logo_alpha.png
    - assets/images/logo_dev.png
    - assets/images/gift.png
    - assets/images/soli.png
    - assets/images/eclair.png
    - assets/images/login.svg
    - assets/web/back.webp
    - assets/web/AMAP.webp
    - assets/web/Calendrier.webp
    - assets/web/Cine.webp
    - assets/web/Parametres.webp
    - assets/web/Pret.webp
    - assets/web/Tombola.webp
    - assets/web/Vote.webp
    - assets/my_document.pdf
    - assets/images/bird.png
    - assets/images/pipe.png
    - assets/images/logo_flappybird.svg
    - assets/images/helloasso.svg

  uses-material-design: true
