name: myecl
description: MyECL est l'application des Centraliens de Lyon, conçue par ÉCLAIR

publish_to: "none"
version: 0.9.0+122

environment:
  sdk: ^3.3.0
  flutter: ^3.22.1

dependencies:
  auto_size_text: ^3.0.0
  badges: ^3.1.1
  collection: ^1.16.0
  crypto: ^3.0.2
  datetime_picker_formfield: ^2.0.1
  device_info_plus: ^9.1.2
  diacritic: ^0.1.5
  dotenv: ^4.0.1
  firebase_core: ^2.25.5
  either_dart: ^1.0.0
  firebase_messaging: ^14.7.17
  fl_chart: ^0.67.0
  flash: ^3.0.5+1
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.0
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.20.0
  flutter_local_notifications: ^16.3.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.1
  heroicons: ^0.10.0
  hooks_riverpod: ^2.1.1
  http: ^1.0.0
  http_parser: ^4.0.2
  image: ^4.0.15
  image_cropper: ^5.0.0
  image_picker: ^1.0.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  load_switch: ^2.0.5
  mocktail: ^1.0.3
  numberpicker: ^2.1.1
  package_info_plus: ^6.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  rxdart: ^0.27.7
  qlevar_router: ^1.9.0
  shared_preferences: ^2.1.1
  smooth_page_indicator: ^1.0.0+2
  syncfusion_flutter_calendar: ^25.1.37+1
  timezone: ^0.9.0
  tuple: ^2.0.0
  universal_html: ^2.0.8
  vector_math: ^2.1.2
  zxcvbn: ^1.0.0
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.5
  pdfx: ^2.6.0
  file_saver: ^0.2.12

dev_dependencies:
  dependency_validator: ^3.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/images/logo_prod.png
    - assets/images/logo_alpha.png
    - assets/images/logo_dev.png
    - assets/images/gift.png
    - assets/images/soli.png
    - assets/images/eclair.png
    - assets/images/login.svg
    - assets/web/back.webp
    - assets/web/AMAP.webp
    - assets/web/Calendrier.webp
    - assets/web/Ciné.webp
    - assets/web/Parametres.webp
    - assets/web/Pret.webp
    - assets/web/Tombola.webp
    - assets/web/Vote.webp
    - assets/my_document.pdf
    - assets/images/bird_2.png
    - assets/images/pipe.png
    - assets/images/flap.svg

  uses-material-design: true
